### ISSUE TITLE
Help a newbie with MacOS install

### ISSUE THREAD

**Issue by Newbie2Trinity** [bamhm182/FinTrinity#15]
Hi guys

I'll be straight up and say that I'm a complete newbie to programming. That said I am competent and with the correct advice I can work me way around issues. 

I can not for the life of me get FinTrinity working for my Mac with Python. I've installed all the needed software. I launch Fintrinity with Python 3.7.3 running on MacOS 10.14.4 by double clicking on the GUI.py file (also tried with FinTrinity.py) but unfortunately once terminal launches I get the following message 

Last login: Tue Jun  4 21:32:35 on ttys000
MYUSERNAME-mbp:~ MYUSERNAME$ cd '/Users/MYUSERNAME/Documents/PS Vita - Trinity/Software/FinTrinity-v0.5-Python/' && '/usr/bin/pythonw'  '/Users/MYUSERNAME/Documents/PS Vita - Trinity/Software/FinTrinity-v0.5-Python/GUI.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Users/MYUSERNAME/Documents/PS Vita - Trinity/Software/FinTrinity-v0.5-Python/GUI.py", line 1, in <module>
    from tkinter import *
ImportError: No module named tkinter
MYUSERNAME-mbp:FinTrinity-v0.5-Python MYUSERNAME$ 

At this point I'm completely lost. I'm sorry I'm completely usless at this point but I really want to get my PSvits out of being a pointless brick as Sony made it and join . in on all the fun. 

Please, is there any help out there?

Many thanks

**Comment by bamhm182** [comment]
Sorry, somehow I missed this for a few days. Tkinter is the program used to create the GUI, and according to an article on the python website, it has issues on macOS. The article says you can get around the issues by installing python from python.org rather than using the default built into macOS.

https://www.python.org/download/mac/tcltk/

You said it gives you the exact same message when you run FinTrinity.py? Can I get you to confirm it is the exact same message and that they don't just look similar? FinTrinity.py shouldn't ever be importing tkinter.

**Comment by Newbie2Trinity** [comment]
Hey thanks for getting back to me. Bee so difficult finding some help. It’s appreciated. 

I’m actually using Python to launch the GUI.py and the computer launches both terminal and Python. 

I’m at work at the moment. When I get home i’ll try the FinTrinity.py again and share the message for comparison. 

Thank you again

**Comment by Newbie2Trinity** [comment]
Hey dude. I tried with the FinTrinity file tonight and this is the message I'm receiving, see below. 

I'm using Python Launcher on the file. It opens up in Python, see screen grab. And then opens a terminal window. Any Ideas? 

Python Launcher Window. Do I need to add some code where it says "Command Line"?
<img width="434" alt="Screenshot 2019-06-06 at 21 25 04" src="https://user-images.githubusercontent.com/51384230/59064201-a91ef000-88a1-11e9-8f95-522450d1774d.png">

Terminal window message

Last login: Thu Jun  6 21:24:36 on ttys000
USER-mbp:~ USERNAME$ cd '/Users/USERNAME/PS Vita/FinTrinity-v0.5-Python/' && '/usr/bin/pythonw'  '/Users/USERNAME/PS Vita/FinTrinity-v0.5-Python/FinTrinity.py'  && echo Exit status: $? && exit 1
  File "/Users/USERNAME/PS Vita/FinTrinity-v0.5-Python/FinTrinity.py", line 49
    f'{self.apps_path / account / "_TEMP"} found. QCMA appears to be backing up a game. We will'
                                                                                               ^
SyntaxError: invalid syntax
USER-mbp:FinTrinity-v0.5-Python USERNAME$

**Comment by bamhm182** [comment]
It found a folder /Users/[Your username]/PS Vita/PGAME/[ACCOUNT ID]/_TEMP.

That _TEMP folder appears to mean that QCMA is currently backing up a game. If that is untrue, QCMA may have not finished entirely at some point. Delete that _TEMP folder and re-run it. 

That GUI is something provided with macOS. I haven't seen it before. I would recommend leaving everything in there alone unless you're know what you're changing. 

EDIT: Actually, upon reading that message again, I think it is mad about how I wrote the error message I wanted to pop up. I'll look into it this weekend or tonight. If you want to try again before I look into it, try v0.4.

**Comment by bamhm182** [comment]
Can you try the version here and let me know if it works for you:
https://github.com/bamhm182/FinTrinity/archive/master.zip

**Comment by Newbie2Trinity** [comment]
Hey dude. Thank you for this and sorry I missed you over the weekend. 

I deleted my PS Vita folder created by QCMA and started again to make sure everything was how it was meant to be. 

After reconnecting the Vita I backed up the Ape Quest Game. 

I then download the new master file you shared with me and ran the FinTrinity.py file and got the following message

Last login: Mon Jun 10 13:40:13 on ttys000
USER-mbp:~ USERNAME$ cd '/Users/USERNAME/Desktop/FinTrinity-master/' && '/usr/bin/pythonw'  '/Users/USERNAME/Desktop/FinTrinity-master/FinTrinity.py'  && echo Exit status: $? && exit 1
  File "/Users/USERNAME/Desktop/FinTrinity-master/FinTrinity.py", line 48
    print(f'{self.apps_path / account / "_TEMP"} found. QCMA appears to be backing up a game. We will')
                                                                                                     ^
SyntaxError: invalid syntax
USER-mbp:FinTrinity-master USERNAME$ 

I refreshed the dtata base, quit QCMA and tried again but still the same message.

**Comment by bamhm182** [comment]
Sorry for the super long wait. These past few weeks have really gotten away from me. It should be fixed now. Please try again if you haven't already moved on.
