### ISSUE TITLE
After selecting the game to patch the v.05 versions exits with "No Working Dir Permissions" error

### ISSUE THREAD

**Issue by tboinski** [bamhm182/FinTrinity#17]
I tried the standalone Linux version, it runs fine, displays game selection window. After selecting the game it exits with "No Working Dir Permissions" command.

**Comment by bamhm182** [comment]
It does that if it cannot write to your Desktop or to the file it was launched from. Do you by chance have Windows Controlled folder access turned on? I'm trying to figure out a good way to get around this, but it is proving to be difficult.

**Comment by tboinski** [comment]
Sorry for the long reply. I'm not running the file on Windows, only in openSUSE Leap 15.0 Linux. The FinTrinity-v0.5-Linux file has rwxr-xr-x permissions and is run by the user that is the owner of the file. The File resides in the user home directory and tries to write to a tmp directory where everybody can write.
It closes after selecting a game backup from QCMA directory (also owned by the same user) with the output:

./FinTrinity-v0.5-Linux 
/bin/sh: /tmp/_MEIIZRusy/libreadline.so.7: no version information available (required by /bin/sh)
Invalid MIT-MAGIC-COOKIE-1 keyNo Working Dir Permissions

**Comment by bamhm182** [comment]
Sorry, you said it was Linux. Should have read that better. I don't know what would cause that in Linux... It tries to write to the desktop, and if that fails, it tries to write to the current working directory. If that fails, it shows that message and quits. I'll see if I can figure something out...

**Comment by tboinski** [comment]
I tried to run it as root - it worked, however I do not understand why it fails to work as normal user as it should write into this user home directory...  As root however it hangs during patching and throws an exception as below. It tries to connect to some URL (which one?) and fails on SSL verification. Perhaps some flag should be used telling the code to ignore the certificate verification?

Created Working Directory: /root/Desktop/FinTrinity2019627-202035
Downloading and Extracting Dependencies
Exception in Tkinter callback
Traceback (most recent call last):
  File "urllib/request.py", line 1317, in do_open
  File "http/client.py", line 1229, in request
  File "http/client.py", line 1275, in _send_request
  File "http/client.py", line 1224, in endheaders
  File "http/client.py", line 1016, in _send_output
  File "http/client.py", line 956, in send
  File "http/client.py", line 1392, in connect
  File "ssl.py", line 412, in wrap_socket
  File "ssl.py", line 853, in _create
  File "ssl.py", line 1117, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tkinter/__init__.py", line 1705, in __call__
  File "GUI.py", line 78, in click_confirm
  File "FinTrinity.py", line 96, in download_dependencies
  File "classes/Utils.py", line 95, in download
  File "urllib/request.py", line 247, in urlretrieve
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 543, in _open
  File "urllib/request.py", line 503, in _call_chain
  File "urllib/request.py", line 1360, in https_open
  File "urllib/request.py", line 1319, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
